### ISSUE TITLE
Questions concerning mainly ACF

### ISSUE THREAD

**Issue by joaobcampos** [LDSSA/batch2-BLU02#3] opened 2018-05-14 13:37 UTC
This BLU raised some questions that I would like to understand better (it will be a long post):
Questions 1-3 Learning notebooks 1 & 2
1st:
In the learning notebook it is written: "We should note that setting min_periods to 0 is fine for visualization purposes BUT once you start using trend estimation to prepare your time series for modelling, using min_periods=0 is not ok at all". This raises two questions: what is the min_periods doing to replace the first NaN values and what would be a reasonable option to fill them? The first value that has some meaning?

2nd:
The greater the window size the more high frequencies will be cut. Is there any criterion related to frequency that might be used to choose a size?

3rd:
For the trend estimation: Wouldn't it be more sensible to start with a moving average and then try to fit a linear regression? By making a linear regression aren't we enforcing a linear assumption on the trend where it may not belong?

Notebook 3
4th:
The concept of pacf is somewhat cumbersome. By reading https://stats.stackexchange.com/questions/129052/acf-and-pacf-formula/129374#129374, it is not entirely clear to what the pacf terms will correspond. It seems that I would arbitrarily choose a p and combine them to form a ~y_t. I cannot grasp the intuition behind the equation system they have there.

5th:
In the "Confidence bands" part: "Confidence bands can be computed as the value of the sample autocorrelations ±z1−α/2n√, where z1−α/2 is the quantile 1−α/2 in the Gaussian distribution, e.g. 1.96 for 95% confidence bands." Which Gaussian distribution? The one behind the stationary series for which we are calculating the pacf? This one is a matter of connecting dots.

6th:
At a certain level, pacf and acf seem to be doing the same thing: By how many samples should I lag my series in order to find a strong correlation. I can understand, why this may be useful to choose p. But why q? d's meaning is clear.

7th:
Focusing on p in the ARIMA model, the p will be chosen according to the number of pacf peaks above the confidence interval, but shouldn't the lag play a part in it? I mean, if the lag is 12, I am assuming that the AR will be something as y_t = a_12 y_(t-12), being a_1, a_11 equal to zero.

**Comment by echo66** [comment] 2018-05-14 18:56
> 1st: In the learning notebook it is written: "We should note that setting min_periods to 0 is fine for visualization purposes BUT once you start using trend estimation to prepare your time series for modelling, using min_periods=0 is not ok at all". This raises two questions: what is the min_periods doing to replace the first NaN values and what would be a reasonable option to fill them? The first value that has some meaning?

You can backfill the resulting time series with the values of the original time series at the same indexes.

The first value of what?


> 2nd: The greater the window size the more high frequencies will be cut. Is there any criterion related to frequency that might be used to choose a size?

The thing is: when estimating the trend (and cyclical component), you aren't in local behaviors, you are interested in the long term. If you are interested in extracting the spectral representation of the time series, you can run FFT on it (or wavelet). But that is completely out of scope.


> 3rd: For the trend estimation: Wouldn't it be more sensible to start with a moving average and then try to fit a linear regression? By making a linear regression aren't we enforcing a linear assumption on the trend where it may not belong?

If you are already using a moving average to estimate the trend, why are you also using the linear regression?
And, yes, you are making an assumption on the nature of the trend when you estimate it with a linear regression. But it is way simpler for anyone to understand a line than a spline or something more advanced. Is it the most precise thing ever? Nope, but it works.

**Comment by PedroGFonseca** [comment] 2021-03-21 16:09
Closing due to inactivity

**Closed as completed by PedroGFonseca** 2021-03-21 16:09 UTC
